# Generated by Django 6.0.4 on 2026-05-06 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_alter_restaurant_cuisine_alter_restaurant_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='delivery.customer')),
                ('items', models.ManyToManyField(related_name='carts', to='delivery.item')),
            ],
        ),
    ]
